<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Platforms>x64</Platforms>
		<RuntimeIdentifiers>win-x64;</RuntimeIdentifiers>
		<OutputType>Library</OutputType>
		<WindowsPackageType>None</WindowsPackageType>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<RootNamespace>ReadWriteMemory.External</RootNamespace>
		<IncludeBuildOutput>true</IncludeBuildOutput>
	</PropertyGroup>
	
	<PropertyGroup>
		<Version>1.2.2</Version>
		<Authors>Daiserdyne</Authors>
		<Product>ReadWriteMemoryExternal</Product>
		<Description>A powerfull memory editing library.</Description>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<PackageIcon>Assets\icon.png</PackageIcon>
		<RepositoryUrl>https://github.com/Daiserdyne/ReadWriteMemory</RepositoryUrl>
		<PackageProjectUrl>https://github.com/Daiserdyne/ReadWriteMemory</PackageProjectUrl>
		<PackageReadmeFile>Assets/README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageId>ReadWriteMemory.External</PackageId>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md">
		  <Pack>true</Pack>
		  <PackagePath>Assets</PackagePath>
		  <Link>Assets\README.md</Link>
		</None>
		<None Include="Assets\icon.png" Pack="true" PackagePath="Assets"/>
	</ItemGroup>
</Project>