#pragma warning disable CS1573 // Parameter has no matching param tag in the XML comment (but other parameters do)
//<auto-generated>

using ReadWriteMemory.Shared.Entities;

namespace ReadWriteMemory.Internal;

public partial class RwMemory
{
    /// <summary>
    /// Calls a function inside the process. You just have to know the signature of the function.
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunction(MemoryAddress memoryAddress)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged<void>)targetAddress;

        func();
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionCdecl<TArg1>(MemoryAddress memoryAddress, TArg1 arg1)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Cdecl]<TArg1, void>)targetAddress;

        func(arg1);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionCdecl<TArg1, TArg2>(MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Cdecl]<TArg1, TArg2, void>)targetAddress;

        func(arg1, arg2);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionCdecl<TArg1, TArg2, TArg3>(MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2,
        TArg3 arg3)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Cdecl]<TArg1, TArg2, TArg3, void>)targetAddress;

        func(arg1, arg2, arg3);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionCdecl<TArg1, TArg2, TArg3, TArg4>(MemoryAddress memoryAddress, TArg1 arg1,
        TArg2 arg2, TArg3 arg3, TArg4 arg4)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Cdecl]<TArg1, TArg2, TArg3, TArg4, void>)targetAddress;

        func(arg1, arg2, arg3, arg4);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionCdecl<TArg1, TArg2, TArg3, TArg4, TArg5>(MemoryAddress memoryAddress, TArg1 arg1,
        TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Cdecl]<TArg1, TArg2, TArg3, TArg4, TArg5, void>)targetAddress;

        func(arg1, arg2, arg3, arg4, arg5);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionCdecl<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(MemoryAddress memoryAddress,
        TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Cdecl]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, void>)targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionCdecl<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(MemoryAddress memoryAddress,
        TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Cdecl]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, void>)targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionCdecl<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Cdecl]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, void>)targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionCdecl<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8, TArg9 arg9)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Cdecl]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, void>)
            targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionCdecl<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8, TArg9 arg9, TArg10 arg10)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Cdecl]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, void>)
            targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionStdcall<TArg1>(MemoryAddress memoryAddress, TArg1 arg1)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Stdcall]<TArg1, void>)targetAddress;

        func(arg1);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionStdcall<TArg1, TArg2>(MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Stdcall]<TArg1, TArg2, void>)targetAddress;

        func(arg1, arg2);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionStdcall<TArg1, TArg2, TArg3>(MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2,
        TArg3 arg3)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Stdcall]<TArg1, TArg2, TArg3, void>)targetAddress;

        func(arg1, arg2, arg3);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionStdcall<TArg1, TArg2, TArg3, TArg4>(MemoryAddress memoryAddress, TArg1 arg1,
        TArg2 arg2, TArg3 arg3, TArg4 arg4)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Stdcall]<TArg1, TArg2, TArg3, TArg4, void>)targetAddress;

        func(arg1, arg2, arg3, arg4);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionStdcall<TArg1, TArg2, TArg3, TArg4, TArg5>(MemoryAddress memoryAddress, TArg1 arg1,
        TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Stdcall]<TArg1, TArg2, TArg3, TArg4, TArg5, void>)targetAddress;

        func(arg1, arg2, arg3, arg4, arg5);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionStdcall<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(MemoryAddress memoryAddress,
        TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Stdcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, void>)targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionStdcall<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(MemoryAddress memoryAddress,
        TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Stdcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, void>)targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionStdcall<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Stdcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, void>)targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionStdcall<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8, TArg9 arg9)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Stdcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, void>)
            targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionStdcall<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8, TArg9 arg9, TArg10 arg10)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Stdcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, void>)
            targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionFastcall<TArg1>(MemoryAddress memoryAddress, TArg1 arg1)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Fastcall]<TArg1, void>)targetAddress;

        func(arg1);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionFastcall<TArg1, TArg2>(MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Fastcall]<TArg1, TArg2, void>)targetAddress;

        func(arg1, arg2);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionFastcall<TArg1, TArg2, TArg3>(MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2,
        TArg3 arg3)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Fastcall]<TArg1, TArg2, TArg3, void>)targetAddress;

        func(arg1, arg2, arg3);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionFastcall<TArg1, TArg2, TArg3, TArg4>(MemoryAddress memoryAddress, TArg1 arg1,
        TArg2 arg2, TArg3 arg3, TArg4 arg4)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Fastcall]<TArg1, TArg2, TArg3, TArg4, void>)targetAddress;

        func(arg1, arg2, arg3, arg4);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionFastcall<TArg1, TArg2, TArg3, TArg4, TArg5>(MemoryAddress memoryAddress, TArg1 arg1,
        TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Fastcall]<TArg1, TArg2, TArg3, TArg4, TArg5, void>)targetAddress;

        func(arg1, arg2, arg3, arg4, arg5);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionFastcall<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(MemoryAddress memoryAddress,
        TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Fastcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, void>)targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionFastcall<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Fastcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, void>)targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionFastcall<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Fastcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, void>)targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionFastcall<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8, TArg9 arg9)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Fastcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, void>)
            targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionFastcall<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8, TArg9 arg9, TArg10 arg10)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Fastcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, void>)
            targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionThiscall<TArg1>(MemoryAddress memoryAddress, TArg1 arg1)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Thiscall]<TArg1, void>)targetAddress;

        func(arg1);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionThiscall<TArg1, TArg2>(MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Thiscall]<TArg1, TArg2, void>)targetAddress;

        func(arg1, arg2);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionThiscall<TArg1, TArg2, TArg3>(MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2,
        TArg3 arg3)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Thiscall]<TArg1, TArg2, TArg3, void>)targetAddress;

        func(arg1, arg2, arg3);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionThiscall<TArg1, TArg2, TArg3, TArg4>(MemoryAddress memoryAddress, TArg1 arg1,
        TArg2 arg2, TArg3 arg3, TArg4 arg4)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Thiscall]<TArg1, TArg2, TArg3, TArg4, void>)targetAddress;

        func(arg1, arg2, arg3, arg4);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionThiscall<TArg1, TArg2, TArg3, TArg4, TArg5>(MemoryAddress memoryAddress, TArg1 arg1,
        TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Thiscall]<TArg1, TArg2, TArg3, TArg4, TArg5, void>)targetAddress;

        func(arg1, arg2, arg3, arg4, arg5);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionThiscall<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(MemoryAddress memoryAddress,
        TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Thiscall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, void>)targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionThiscall<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Thiscall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, void>)targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionThiscall<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Thiscall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, void>)targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionThiscall<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8, TArg9 arg9)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Thiscall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, void>)
            targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe void CallFunctionThiscall<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8, TArg9 arg9, TArg10 arg10)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Thiscall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, void>)
            targetAddress;

        func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionCdecl<TResult, TArg1>(MemoryAddress memoryAddress, TArg1 arg1)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Cdecl]<TArg1, TResult>)targetAddress;

        return func(arg1);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionCdecl<TResult, TArg1, TArg2>(MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Cdecl]<TArg1, TArg2, TResult>)targetAddress;

        return func(arg1, arg2);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionCdecl<TResult, TArg1, TArg2, TArg3>(MemoryAddress memoryAddress, TArg1 arg1,
        TArg2 arg2, TArg3 arg3)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Cdecl]<TArg1, TArg2, TArg3, TResult>)targetAddress;

        return func(arg1, arg2, arg3);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionCdecl<TResult, TArg1, TArg2, TArg3, TArg4>(MemoryAddress memoryAddress,
        TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Cdecl]<TArg1, TArg2, TArg3, TArg4, TResult>)targetAddress;

        return func(arg1, arg2, arg3, arg4);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionCdecl<TResult, TArg1, TArg2, TArg3, TArg4, TArg5>(MemoryAddress memoryAddress,
        TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Cdecl]<TArg1, TArg2, TArg3, TArg4, TArg5, TResult>)targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionCdecl<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Cdecl]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TResult>)targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionCdecl<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Cdecl]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TResult>)targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionCdecl<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Cdecl]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TResult>)targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionCdecl<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8, TArg9 arg9)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Cdecl]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TResult>)
            targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult
        CallFunctionCdecl<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10>(
            MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6,
            TArg7 arg7,
            TArg8 arg8, TArg9 arg9, TArg10 arg10)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Cdecl]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TResult>)
            targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionStdcall<TResult, TArg1>(MemoryAddress memoryAddress, TArg1 arg1)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Stdcall]<TArg1, TResult>)targetAddress;

        return func(arg1);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionStdcall<TResult, TArg1, TArg2>(MemoryAddress memoryAddress, TArg1 arg1,
        TArg2 arg2)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Stdcall]<TArg1, TArg2, TResult>)targetAddress;

        return func(arg1, arg2);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionStdcall<TResult, TArg1, TArg2, TArg3>(MemoryAddress memoryAddress, TArg1 arg1,
        TArg2 arg2, TArg3 arg3)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Stdcall]<TArg1, TArg2, TArg3, TResult>)targetAddress;

        return func(arg1, arg2, arg3);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionStdcall<TResult, TArg1, TArg2, TArg3, TArg4>(MemoryAddress memoryAddress,
        TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Stdcall]<TArg1, TArg2, TArg3, TArg4, TResult>)targetAddress;

        return func(arg1, arg2, arg3, arg4);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionStdcall<TResult, TArg1, TArg2, TArg3, TArg4, TArg5>(MemoryAddress memoryAddress,
        TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Stdcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TResult>)targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionStdcall<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Stdcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TResult>)targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionStdcall<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Stdcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TResult>)targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionStdcall<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Stdcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TResult>)
            targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionStdcall<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8, TArg9 arg9)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Stdcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TResult>)
            targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult
        CallFunctionStdcall<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10>(
            MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6,
            TArg7 arg7,
            TArg8 arg8, TArg9 arg9, TArg10 arg10)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Stdcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TResult
                >)targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionFastcall<TResult, TArg1>(MemoryAddress memoryAddress, TArg1 arg1)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Fastcall]<TArg1, TResult>)targetAddress;

        return func(arg1);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionFastcall<TResult, TArg1, TArg2>(MemoryAddress memoryAddress, TArg1 arg1,
        TArg2 arg2)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Fastcall]<TArg1, TArg2, TResult>)targetAddress;

        return func(arg1, arg2);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionFastcall<TResult, TArg1, TArg2, TArg3>(MemoryAddress memoryAddress, TArg1 arg1,
        TArg2 arg2, TArg3 arg3)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Fastcall]<TArg1, TArg2, TArg3, TResult>)targetAddress;

        return func(arg1, arg2, arg3);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionFastcall<TResult, TArg1, TArg2, TArg3, TArg4>(MemoryAddress memoryAddress,
        TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Fastcall]<TArg1, TArg2, TArg3, TArg4, TResult>)targetAddress;

        return func(arg1, arg2, arg3, arg4);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionFastcall<TResult, TArg1, TArg2, TArg3, TArg4, TArg5>(MemoryAddress memoryAddress,
        TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Fastcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TResult>)targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionFastcall<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Fastcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TResult>)targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionFastcall<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Fastcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TResult>)targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionFastcall<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Fastcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TResult>)
            targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionFastcall<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8, TArg9 arg9)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Fastcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TResult>)
            targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult
        CallFunctionFastcall<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10>(
            MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6,
            TArg7 arg7,
            TArg8 arg8, TArg9 arg9, TArg10 arg10)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Fastcall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10,
                TResult>)targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionThiscall<TResult, TArg1>(MemoryAddress memoryAddress, TArg1 arg1)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Thiscall]<TArg1, TResult>)targetAddress;

        return func(arg1);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionThiscall<TResult, TArg1, TArg2>(MemoryAddress memoryAddress, TArg1 arg1,
        TArg2 arg2)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Thiscall]<TArg1, TArg2, TResult>)targetAddress;

        return func(arg1, arg2);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionThiscall<TResult, TArg1, TArg2, TArg3>(MemoryAddress memoryAddress, TArg1 arg1,
        TArg2 arg2, TArg3 arg3)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Thiscall]<TArg1, TArg2, TArg3, TResult>)targetAddress;

        return func(arg1, arg2, arg3);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionThiscall<TResult, TArg1, TArg2, TArg3, TArg4>(MemoryAddress memoryAddress,
        TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Thiscall]<TArg1, TArg2, TArg3, TArg4, TResult>)targetAddress;

        return func(arg1, arg2, arg3, arg4);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionThiscall<TResult, TArg1, TArg2, TArg3, TArg4, TArg5>(MemoryAddress memoryAddress,
        TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Thiscall]<TArg1, TArg2, TArg3, TArg4, TArg5, TResult>)targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionThiscall<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func = (delegate* unmanaged[Thiscall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TResult>)targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionThiscall<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Thiscall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TResult>)targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionThiscall<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Thiscall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TResult>)
            targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult CallFunctionThiscall<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>(
        MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7,
        TArg8 arg8, TArg9 arg9)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Thiscall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TResult>)
            targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
    }

    /// <summary>
    /// <inheritdoc cref="CallFunction"/>
    /// </summary>
    /// <param name="memoryAddress"></param>
    public unsafe TResult
        CallFunctionThiscall<TResult, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10>(
            MemoryAddress memoryAddress, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6,
            TArg7 arg7,
            TArg8 arg8, TArg9 arg9, TArg10 arg10)
    {
        var targetAddress = GetTargetAddress(memoryAddress);

        var func =
            (delegate* unmanaged[Thiscall]<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10,
                TResult>)targetAddress;

        return func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
    }
}